# This docker-compose file is meant to be run for development and serves as a
# guideline for a production deployment.
version: '3.8'

# Techsuite consists of 3 services:
#  1. React client at port 3000.
#  2. Flask REST API and websocket server at port 5000.
#  3. PostgreSQL database server at port 4000.
services:
    client:
        build:
            context: client
            dockerfile: Dockerfile
        ports:
            - 3000:80
    db:
        build:
            context: server
            dockerfile: Dockerfile.db
        environment:
            # These credentials are used for creating the db superuser. They're not
            # the credentials we use from the API side.
            POSTGRES_PASSWORD: 1989
            POSTGRES_USER: admin
        ports:
            - 5432:5432
        volumes:
            - db-data:/var/lib/postgres/data
    api:
        build:
            context: server
            dockerfile: Dockerfile.api
        depends_on:
            - db
        environment:
            PORT: 5000
            DATABASE_URI: postgresql://tim:1989@db:5432/techsuite
            BASE_URI: http://localhost:5000/api
        ports:
            - 5000:5000
volumes:
    db-data:
