FROM postgres:14-alpine

EXPOSE 4000

WORKDIR /

COPY db-init.sh /docker-entrypoint-initdb.d

# Create all the tables and initialise the database with a set of existing 
# channels, users, connections, messages, etc.
# COPY ./seeds/full-2.sql /docker-entrypoint-initdb.d

# No need to override the default postgres CMD in this Dockerfile.
