#!/bin/sh
# Setup tool for starting the server and setting up the database

targetPort=5000
helpLog="Usage: $0 [--setup | --reset | --wipe] <port>"
while test $# -gt 0; do
    case "$1" in
        -h)
            echo "$helpLog"
            exit 0
            ;;
        --setup)
            (echo "create_all()" | python3 -i src/db_manage.py 2> /dev/null) && echo "Done"
            shift
            ;;
        --reset)
            (printf "drop_all()\ncreate_all()" | python3 -i src/db_manage.py 2> /dev/null) && echo "Done"
            
            shift
            ;;
        --wipe)
            (echo "drop_all()" | python3 -i src/db_manage.py 2> /dev/null) && echo "Done"
            exit 0
            ;;
        *)
            if echo $1 | egrep '[0-9]+' > /dev/null 2> /dev/null; then
                targetPort=$1
            else
                echo "$helpLog"
                exit 1
            fi
            shift
            ;;
    esac
done

python3 src/server.py "$targetPort"
