#!/usr/bin/perl -w
# Given a maps all indentations from 2 to 4

$argc = $#ARGV + 1;
if ($argc < 1) {
    print("Usage: $0 <targetfile>\n");
    exit 1;
}

$targetFilename = $ARGV[0];
print("|===== Formatting file '$targetFilename' to 4-space indentation =====|\n"); 

open my $file, "<", "$targetFilename" or die("Failed to open $targetFilename: $!");
@lines = <$file>;
foreach my $line (@lines) {
    $line =~ /^(\s*)/;
    $existingIndent = $1;
    $newIndent = $existingIndent . $existingIndent;
    $line =~ s/^$existingIndent/$newIndent/g;
}
close($file);

open $file, ">", "$targetFilename-output" or die("Failed to open $targetFilename: $!");
foreach my $line (@lines) {
    print $file "$line";
}
close($file);
