#!/usr/bin/perl -w

$argc = $#ARGV + 1;
if ($argc < 2) {
     print("Usage: $0 <targetfile> <num of spaces>\n");
     exit 1;
}

$targetFilename = $ARGV[0];
$numSpaces = $ARGV[1];
print("|===== Formatting file '$targetFilename' to ${numSpaces}-space indentation =====|\n"); 

open my $file, "<", "$targetFilename" or die("Failed to open $targetFilename: $!");
@lines = <$file>;
foreach my $line (@lines) {
     $line =~ s/^ /  /;
}
close($file);

open $file, ">", "$targetFilename-output" or die("Failed to open $targetFilename: $!");
foreach my $line (@lines) {
     print $file "$line";
}
close($file);
